config/routes.rb
Rails.application.routes.draw do
  resources :shops

  get 'showmap', to: 'shops#show'

  root to: 'shops#index'
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index

  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopassist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header id="applicationHeader">
  <div class="login"></div>
  <div class="navigation-menu">
    <%= image_tag('logo.png') %>
    <ul>
      <li id="groceries" class="navigation-option">My List</li>
      <li id="shops" class="navigation-option">Find Shop</li>
      <li id="findProduct" class="navigation-option">Find product</li>
      <li id="artisans" class="navigation-option">Find Artisan</li>
      <li id="online" class="navigation-option"><%= link_to 'Purchase', showmap_path %></li>
      <li id="feedback" class="navigation-option">Feedback</li>
    </ul>
  </div>
</header>

<%= yield %>

</body>
</html>

app/views/shops/_artisans.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="167.597px" height="113.606px" viewBox="90 60 167.597 113.606" enable-background="new 0 0 167.597 113.606"
   xml:space="preserve">
<g opacity="0.8" transform="scale(2)" fill="#FFFFFF">
  <path fill="" d="M74.554,49.186c0,0-13.369-0.564-14.435,11.234s8.27,18.527,16.871,18.146
    c8.695-0.385,18.914-4.338,20.018-20.703c0.228-2.588,0.913-12.482-8.449-19.485c-0.989-0.913-3.425-3.577,1.827,0.609
    s8.296,10.744,7.84,19.643c-0.457,8.899-4.719,21.153-21.235,22.143c-12.559-0.076-19.18-10.884-18.572-18.724
    C59.027,54.209,62.985,49.262,74.554,49.186z"/>
  <path fill="" d="M98.834,55.96c0,0-0.19-2.359,1.636-4.034s4.034-2.055,4.034-2.055s0.381-0.343,0.647-0.761
    c0.266-0.419,2.664-3.463,2.664-3.463l-2.74,4.376c0,0-0.266,6.051-5.29,6.622c-0.913,0.228-0.913,0.228-0.913,0.228L98.834,55.96z
    "/>
  <path fill="" d="M96.331,55.91c0,0-0.626-2.176-2.787-3.077c-2.162-0.901-4.222-0.518-4.222-0.518s-0.448-0.182-0.822-0.47
    c-0.374-0.288-3.495-2.228-3.495-2.228l3.868,3.022c0,0,2.265,5.333,6.855,4.197c0.876-0.095,0.876-0.095,0.876-0.095L96.331,55.91
    z"/>
  <path fill="" d="M97.843,50.143c0,0-0.133-1.655,1.148-2.83c1.282-1.175,2.83-1.442,2.83-1.442s0.267-0.24,0.454-0.534
    c0.187-0.294,1.869-2.43,1.869-2.43l-1.922,3.071c0,0-0.187,4.245-3.711,4.646c-0.641,0.16-0.641,0.16-0.641,0.16L97.843,50.143z"
    />
  <path fill="" d="M95.876,50.237c0,0-0.892-1.401-2.633-1.555c-1.742-0.155-3.15,0.577-3.15,0.577s-0.36-0.029-0.688-0.149
    c-0.328-0.12-2.972-0.796-2.972-0.796l3.402,1.274c0,0,2.713,3.269,5.794,1.439c0.613-0.263,0.613-0.263,0.613-0.263L95.876,50.237
    z"/>
  <path fill="" d="M96.636,45.59c0,0-0.254-1.39,0.732-2.494c0.985-1.103,2.274-1.461,2.274-1.461s0.206-0.226,0.339-0.491
    c0.133-0.265,0.845-1.247,0.845-1.247l-0.836,1.794c0,0,0.202,3.61-2.748,4.248c-0.529,0.19-0.529,0.19-0.529,0.19L96.636,45.59z"
    />
  <path fill="" d="M94.406,46.224c0,0-0.809-1.017-2.111-1.067c-1.301-0.05-2.261,0.553-2.261,0.553s-0.269-0.008-0.524-0.085
    c-0.255-0.078-1.321-0.228-1.321-0.228l1.69,0.57c0,0,2.355,2.35,4.43,0.859c0.424-0.221,0.424-0.221,0.424-0.221L94.406,46.224z"
    />
  <path fill="" d="M94.618,42.238c0,0-0.442-1.214,0.277-2.359c0.719-1.145,1.825-1.665,1.825-1.665s0.151-0.235,0.23-0.494
    c0.08-0.259,0.297-0.614,0.297-0.614l-0.205,1.106c0,0,0.736,3.222-1.825,4.25c-0.447,0.252-0.447,0.252-0.447,0.252L94.618,42.238
    z"/>
  <path fill="" d="M92.511,42.89c0,0-0.827-0.789-1.945-0.709c-1.118,0.081-1.859,0.684-1.859,0.684s-0.231,0.019-0.459-0.023
    c-0.228-0.042-0.573-0.021-0.573-0.021L88.61,43.1c0,0,2.324,1.778,3.899,0.313c0.333-0.228,0.333-0.228,0.333-0.228L92.511,42.89z
    "/>
  <path fill="" d="M92.241,39.439c0,0-0.592-1.148-0.025-2.376c0.567-1.228,1.598-1.884,1.598-1.884s0.12-0.253,0.166-0.519
    c0.046-0.267,0.099-0.35,0.099-0.35l0.055,0.826c0,0,1.139,3.104-1.27,4.448c-0.412,0.307-0.412,0.307-0.412,0.307L92.241,39.439z"
    />
  <path fill="" d="M90.037,40.285c0,0-0.534-0.703-1.42-0.753c-0.886-0.05-1.55,0.348-1.55,0.348s-0.183-0.009-0.355-0.065
    s-0.236-0.051-0.236-0.051l0.481,0.289c0,0,1.564,1.63,3.003,0.641c0.292-0.145,0.292-0.145,0.292-0.145L90.037,40.285z"/>
  <path fill="" d="M87.394,38.055c0,0-0.384-0.506-1.022-0.542c-0.637-0.036-1.116,0.25-1.116,0.25s-0.132-0.006-0.256-0.047
    c-0.124-0.04-0.17-0.037-0.17-0.037l0.346,0.208c0,0,1.125,1.173,2.161,0.461c0.21-0.104,0.21-0.104,0.21-0.104L87.394,38.055z"/>
  <path fill="" d="M86.493,36.16c0,0-0.103-0.697-0.704-1.073c-0.601-0.376-1.219-0.353-1.219-0.353s-0.125-0.076-0.224-0.182
    s-0.145-0.126-0.145-0.126l0.226,0.387c0,0,0.468,1.742,1.855,1.603c0.26,0.011,0.26,0.011,0.26,0.011L86.493,36.16z"/>
  <path fill="" d="M89.892,37.412c0,0-0.504-0.761-0.199-1.666c0.306-0.905,0.982-1.444,0.982-1.444s0.065-0.186,0.077-0.377
    c0.012-0.191,0.043-0.253,0.043-0.253l0.102,0.576c0,0,1.038,2.093-0.555,3.22c-0.266,0.247-0.266,0.247-0.266,0.247L89.892,37.412
    z"/>
  <path fill="" d="M87.9,36.222c0,0-0.636-0.497-0.631-1.341s0.423-1.486,0.423-1.486s0.003-0.174-0.04-0.338
    s-0.034-0.224-0.034-0.224l0.246,0.454c0,0,1.456,1.463,0.431,2.855c-0.155,0.282-0.155,0.282-0.155,0.282L87.9,36.222z"/>
</g>
</svg>

app/views/shops/_list.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="167.597px" height="113.606px" viewBox="90 60 167.597 113.606" enable-background="new 0 0 167.597 113.606"
   xml:space="preserve">
<g opacity="0.8" transform="scale(2)" fill="#FFFFFF">
  <path id="path8040_24_" inkscape:connector-curvature="0" opacity="0.8" d="M63.838,37.942v37.722h30.178V37.942
    H63.838z M67.61,41.714h22.633v30.178H67.61V41.714z M71.383,48.63v1.886h8.488V48.63H71.383z M71.383,52.402v1.886h15.089v-1.886
    H71.383z M71.383,56.174v1.886h10.374v-1.886H71.383z M71.383,59.946v1.886h8.488v-1.886H71.383z M71.383,63.719v1.886h14.146
    v-1.886H71.383z"/>
</g>
</svg>

app/views/shops/_location.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   width="167.597px" height="113.606px" viewBox="90 60 167.597 113.606" fill="#000000" enable-background="new 0 0 167.597 113.606"
   xml:space="preserve">
<g opacity="0.8" transform="scale(2)" fill="#000000">
  <path id="path7974_11_" inkscape:connector-curvature="0" opacity="0.8" d="M81.202,32.909
    c-7.93,0-14.345,6.147-14.345,13.745c0,4.869,1.706,7.729,3.838,10.363c2.133,2.633,4.741,4.969,6.248,8.537
    c1.674,3.964,2.405,7.891,2.97,10.792c0.283,1.45,0.548,2.66,0.812,3.436c0.131,0.388,0.26,0.674,0.364,0.805
    c0.104,0.132,0.103,0.107,0.111,0.107c0,0,0.012,0.029,0.111-0.107c0.103-0.131,0.231-0.417,0.364-0.805
    c0.265-0.776,0.53-1.986,0.813-3.436c0.564-2.901,1.296-6.828,2.97-10.792c1.507-3.568,4.115-5.904,6.248-8.537
    c2.132-2.633,3.838-5.493,3.838-10.363c0-7.599-6.415-13.745-14.346-13.746H81.202z M81.202,41.983c2.678,0,4.848,2.079,4.848,4.645
    c0,2.566-2.169,4.644-4.847,4.644c-2.678,0-4.847-2.078-4.847-4.644C76.355,44.062,78.525,41.983,81.202,41.983z"/>
</g>
</svg>

app/views/shops/index.html.erb
<header>
  <ul id="navigation">
    <li id="shops" class="navigation-option select">
      <%= render partial: 'location' %>
    </li>
    <li id="artisans" class="navigation-option">
      <%= render partial: 'artisans' %>
    </li>
    <li id="groceries" class="navigation-option">
      <%= render partial: 'list' %>
    </li>
  </ul>
</header>


<div id="shopsList" class="main-menu-list">
  <div class="searchbox">
    <input id="storesearch" type="search" placeholder="search ..." value="Zürich">
  </div>
  <%= link_to showmap_path do %>
    <div id="migros" class="shop">
      <div class="shop-title">
        Migros,
        <span>Limmatplatz</span>
        <span class="distance">200m</span>
      </div>
      <div class="rating">&#x2605; &#x2605; &#x2605; &#x2605;</div>
      <%= image_tag('migros_limmatplatz.jpg') %>
    </div>
  <% end %>

  <%= link_to showmap_path do %>
    <div id="coop" class="shop">
      <div class="shop-title">
        Coop,
        <span>Röntgenstrasse 20</span>
        <span class="distance">400m</span>
      </div>
      <div class="rating">&#x2605; &#x2605; &#x2605; &#x2605;</div>
      <%= image_tag('coop_rontgestrasse.jpg') %>
    </div>
  <% end %>

  <%= link_to showmap_path do %>
    <div id="denner" class="shop">
      <div class="shop-title">
        Denner,
        <span>Röntgenstrasse 20</span>
        <span class="distance">1.5km</span>
      </div>
      <div class="rating">&#x2605; &#x2605; &#x2605;</div>
      <%= image_tag('denner.jpg') %>
    </div>
  <% end %>
</div>

<div id="artisansList" class="main-menu-list">
  <div class="searchbox">
    <input id="storesearch" type="search" placeholder="search ..." value="Zürich">
  </div>

  <%= link_to showmap_path do %>
    <div id="bachmann" class="shop">
      <div class="shop-title">
        Confiserie Bachmann,
        <span>HB Zürich</span>
        <span class="distance">400m</span>
      </div>
      <div class="rating">&#x2605; &#x2605; &#x2605; &#x2605; &#x2605;</div>
      <%= image_tag('bachmann.jpg') %>
    </div>
  <% end %>

  <%= link_to showmap_path do %>
    <div id="spruengli" class="shop">
      <div class="shop-title">
        Sprüngli,
        <span>Röntgenstrasse 20</span>
        <span class="distance">1.5km</span>
      </div>
      <div class="rating">&#x2605; &#x2605; &#x2605; &#x2605; &#x2605;</div>
      <%= image_tag('sprungli.jpg') %>
    </div>
  <% end %>

  <%= link_to showmap_path do %>
    <div id="jakob" class="shop">
      <div class="shop-title">
        St. Jakob Bäckerei,
        <span>Limmatplatz</span>
        <span class="distance">200m</span>
      </div>
      <div class="rating">&#x2605; &#x2605; &#x2605;</div>
      <%= image_tag('st_jakob_bakerei.jpg') %>
    </div>
  <% end %>
</div>

<div id="groceriesList" class="main-menu-list">

  <div id="list1" class="shop">
    <div class="list-title">
      Saturday, 11/07/2015
    </div>
    <ul>
      <li>&#x2713; bread</li>
      <li>milk</li>
      <li>&#x2713; oranges</li>
      <li>&#x2713; apples</li>
      <li>&#x2713; pasta (gluten-free)</li>
      <li>&#x2713; onions</li>
      <li>tomatoes</li>
    </ul>
  </div>


  <%= 10.times do |x| %>
    <%= link_to root_path do %>
      <div id="list2" class="shop">
        <div class="list-title collapsed">
          <%= (Time.new - 3*x.days).strftime('%A, %d/%m/%Y') %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div id="findProductList" class="main-menu-list">
  <div class="searchbox">
    <input id="storesearch" type="search" placeholder="search ..." value="pasta gluten free">
  </div>

  <div id="pasta1" class="product product-detail">
    <div class="product-title">
      Pasta Barilla
    </div>
    <%= image_tag('pasta1.jpg') %>
    <div class="product-rating">&#x2605; &#x2605; &#x2605; &#x2605; &#x2605;</div>
  </div>

  <div id="pasta2" class="product product-detail">
    <div class="product-title">
      Pasta Ronzoni
    </div>
    <%= image_tag('pasta2.jpg') %>
    <div class="product-rating">&#x2605; &#x2605; &#x2605;</div>
  </div>

  <div id="pasta3" class="product product-detail">
    <div class="product-title">
      Pasta Mueller's
    </div>
    <%= image_tag('pasta3.jpg') %>
    <div class="product-rating">&#x2605; &#x2605;</div>
  </div>

  <div id="pasta4" class="product product-detail">
    <div class="product-title">
      Pasta Heartland
    </div>
    <%= image_tag('pasta4.jpg') %>
    <div class="product-rating">&#x2605; &#x2605; &#x2605; &#x2605;</div>
  </div>

  <div id="pasta1" class="product product-description">
    <div class="product-title">
      Pasta Barilla
    </div>
    <div class="product-rating">&#x2605; &#x2605; &#x2605; &#x2605; &#x2605;</div>
  </div>
</div>

app/views/shops/show.html.erb
<div class="wrapper">
  <div id="pin"></div>

  <div id="banana" class="pin" style="top: 400px; left: 700px"></div>
  <div id="sandwich" class="pin" style="top: 690px; left: 90px"></div>
  <div id="tuna" class="pin" style="top: 467px; left: 180px"></div>
  <div id="rice" class="pin" style="top: 820px; left: 400px"></div>
  <div id="tomatoes" class="pin" style="top: 400px; left: 430px"></div>
  <div id="bread" class="pin" style="top: 170px; left: 613px"></div>
  <div id="fish" class="pin" style="top: 467px; left: 120px"></div>

  <div class="store-info pin" style="top: 375px; left: 47px"></div>
  <div class="store-info pin" style="top: 1461px; left: 47px"></div>
  <div class="store-info pin" style="top: 880px; left: 47px"></div>


  <div class="map"><%= image_tag('floorplan2.jpg') %></div>
  <div id="find">
    <div id="toggleMenu"></div>
    <div id="mainMenu" class="menu">
      <ul>
        <li id="storeInfos">store infos</li>
        <li id="showGroceryList">grocery list</li>
        <li class="back"><%= link_to 'back', shops_path %></li>
      </ul>
    </div>
    <div id="products" class="menu">
      <ul>
        <li><input type="search"></li>
      </ul>
    </div>
    <div id="groceryList" class="menu">
      <ul>
        <li id="banana" class="xproduct checked">gazapcho<span class="addProduct">+</span></li>
        <li id="sandwich" class="xproduct checked">sandwich<span class="addProduct">+</span></li>
        <li id="tuna" class="xproduct">tuna<span class="addProduct">+</span></li>
        <li id="rice" class="xproduct">rice<span class="addProduct">+</span></li>
        <li id="fish" class="xproduct checked">fish<span class="addProduct">+</span></li>
        <li id="tomatoes" class="xproduct">tomatoes<span class="addProduct">+</span></li>
        <li id="bread" class="xproduct">bread<span class="addProduct">+</span></li>
        <li class="back">back</li>
      </ul>
    </div>
  </div>
</div>